Revert "Re-enable -Wrange-loop-construct warning in 1P."
This reverts commit a6403bc33b93def76435c7251820521d10cbe3b7.

Reason for revert: Causes the following build breakage:
device/google/sw5100/powerstats/PmicStateResidencyDataProvider.cpp:106:25: error: loop variable '[regulatorAddress, regulatorInfo]' creates a copy from type 'const value_type' (aka 'const pair<const int, aidl::android::hardware::power::stats::RegulatorInfo>') [-Werror,-Wrange-loop-construct]
106 | for (const auto [regulatorAddress, regulatorInfo] : regulatorsMap) {
| ^
device/google/sw5100/powerstats/PmicStateResidencyDataProvider.cpp:106:14: note: use reference type 'const value_type &' (aka 'const pair<const int, aidl::android::hardware::power::stats::RegulatorInfo> &') to prevent copying
106 | for (const auto [regulatorAddress, regulatorInfo] : regulatorsMap) {
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| &

Bug: 153747076
Change-Id: I0c1e8533a3994d727107d24956ce7b272b1bcbd7