soong: Adapt PathForSourceRelaxed for Android U
* Since existsWithDependencies change its param from
  PathContext to PathGlobContext, we should use modCtx instead of ctx.

Fix:
build/soong/android/paths.go:1088:37: too many values in struct literal of type SourcePath
build/soong/android/paths.go:1180:41: cannot use ctx (variable of type PathContext) as PathGlobContext value in argument to existsWithDependencies: PathContext does not implement PathGlobContext (missing method GlobWithDeps)

Change-Id: I5a88564baf6551b3e512aaa23bdad827d57ee8bd